# https://mtyurt.net/post/docker-how-to-increase-number-of-open-files-limit.html
# https://docs.docker.com/compose/compose-file/compose-file-v3/#ulimits
# https://www.cyberciti.biz/faq/linux-unix-nginx-too-many-open-files/

version: "3.5"
services:
  #api1: &app # API - Instância 01
  #  build: .
  #  hostname: api1
  #  depends_on:
  #    - db
  #  expose:
  #    - "80"
  #  environment:
  #    NAME: api1
  #    SLOW_QUERY_ALERT: false
  #  deploy:
  #    resources:
  #      limits:
  #        cpus: "0.25"
  #        memory: "0.5GB"
  #  ulimits:
  #    nproc: 65536
  #    nofile:
  #      soft: 65536
  #      hard: 65536

  #api2: # API - Instância 01
  #  <<: *app
  #  hostname: api2

  #nginx: # Load Balancer
  #  image: nginx:1.25.2
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #  depends_on:
  #    - api1
  #    # - api2
  #  ports:
  #    - "9999:9999"
  #  deploy:
  #    resources:
  #      limits:
  #        cpus: "0.25"
  #        memory: "0.5GB"
  #  ulimits:
  #    nproc: 65536
  #    nofile:
  #      soft: 65536
  #      hard: 65536

  db: # Banco de dados
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"
